import dotenv from 'dotenv';
import path from 'path';
import AWS from 'aws-sdk';

// Load environment variables
dotenv.config({ path: path.resolve(__dirname, '../../.env') });

const checkCloudWatchPermissions = async () => {
  try {
    console.log('=== CloudWatch Permissions Check ===');
    
    // Configure AWS
    AWS.config.update({
      accessKeyId: process.env['AWS_ACCESS_KEY_ID'],
      secretAccessKey: process.env['AWS_SECRET_ACCESS_KEY'],
      region: process.env['AWS_REGION'],
    });

    const cloudWatchLogs = new AWS.CloudWatchLogs();
    const logGroupName = process.env['CLOUDWATCH_LOG_GROUP'] || 'derji-productions-api';

    console.log('Checking AWS credentials and permissions...');
    console.log('Region:', process.env['AWS_REGION']);
    console.log('Log Group:', logGroupName);

    // Test 1: List log groups (basic read permission)
    console.log('\n1. Testing DescribeLogGroups permission...');
    try {
      const result = await cloudWatchLogs.describeLogGroups({
        logGroupNamePrefix: logGroupName,
      }).promise();
      
      console.log('✅ DescribeLogGroups: SUCCESS');
      console.log(`Found ${result.logGroups?.length || 0} matching log groups`);
      
      const existingGroup = result.logGroups?.find(group => group.logGroupName === logGroupName);
      if (existingGroup) {
        console.log(`✅ Log group "${logGroupName}" already exists`);
      } else {
        console.log(`ℹ️  Log group "${logGroupName}" does not exist yet`);
      }
    } catch (error) {
      console.log('❌ DescribeLogGroups: FAILED');
      console.error('Error:', error);
      return;
    }

    // Test 2: Create log group (if it doesn't exist)
    console.log('\n2. Testing CreateLogGroup permission...');
    try {
      await cloudWatchLogs.createLogGroup({
        logGroupName: logGroupName,
      }).promise();
      console.log('✅ CreateLogGroup: SUCCESS (log group created)');
    } catch (error: any) {
      if (error.code === 'ResourceAlreadyExistsException') {
        console.log('✅ CreateLogGroup: SUCCESS (log group already exists)');
      } else {
        console.log('❌ CreateLogGroup: FAILED');
        console.error('Error:', error);
        return;
      }
    }

    // Test 3: Create log stream
    const logStreamName = `test-stream-${Date.now()}`;
    console.log('\n3. Testing CreateLogStream permission...');
    try {
      await cloudWatchLogs.createLogStream({
        logGroupName: logGroupName,
        logStreamName: logStreamName,
      }).promise();
      console.log('✅ CreateLogStream: SUCCESS');
    } catch (error) {
      console.log('❌ CreateLogStream: FAILED');
      console.error('Error:', error);
      return;
    }

    // Test 4: Put log events
    console.log('\n4. Testing PutLogEvents permission...');
    try {
      await cloudWatchLogs.putLogEvents({
        logGroupName: logGroupName,
        logStreamName: logStreamName,
        logEvents: [
          {
            timestamp: Date.now(),
            message: JSON.stringify({
              level: 'info',
              message: 'CloudWatch permissions test',
              timestamp: new Date().toISOString(),
              test: true,
            }),
          },
        ],
      }).promise();
      console.log('✅ PutLogEvents: SUCCESS');
    } catch (error) {
      console.log('❌ PutLogEvents: FAILED');
      console.error('Error:', error);
      return;
    }

    // Test 5: List log streams
    console.log('\n5. Testing DescribeLogStreams permission...');
    try {
      const result = await cloudWatchLogs.describeLogStreams({
        logGroupName: logGroupName,
        orderBy: 'LastEventTime',
        descending: true,
        limit: 5,
      }).promise();
      console.log('✅ DescribeLogStreams: SUCCESS');
      console.log(`Found ${result.logStreams?.length || 0} log streams`);
    } catch (error) {
      console.log('❌ DescribeLogStreams: FAILED');
      console.error('Error:', error);
      return;
    }

    // Cleanup: Delete test log stream
    console.log('\n6. Cleaning up test log stream...');
    try {
      await cloudWatchLogs.deleteLogStream({
        logGroupName: logGroupName,
        logStreamName: logStreamName,
      }).promise();
      console.log('✅ Test log stream deleted');
    } catch (error) {
      console.log('⚠️  Could not delete test log stream (this is okay)');
    }

    console.log('\n=== All Permissions Check PASSED ===');
    console.log('Your AWS credentials have the necessary CloudWatch permissions.');
    console.log('If you\'re still not seeing logs, check:');
    console.log('1. Application is actually running in production mode');
    console.log('2. Log level is set correctly (info or lower)');
    console.log('3. Logs are being generated by the application');
    console.log('4. CloudWatch console region matches your AWS_REGION');

  } catch (error) {
    console.error('Permissions check failed:', error);
    console.log('\n=== Required CloudWatch Permissions ===');
    console.log('Your IAM user/role needs these permissions:');
    console.log('- logs:CreateLogGroup');
    console.log('- logs:CreateLogStream');
    console.log('- logs:PutLogEvents');
    console.log('- logs:DescribeLogGroups');
    console.log('- logs:DescribeLogStreams');
  }
};

// Run the check
checkCloudWatchPermissions().then(() => {
  process.exit(0);
}).catch((error) => {
  console.error('Permission check script failed:', error);
  process.exit(1);
});